application: appredictor
version: 6
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

libraries:
 - name: webapp2
   version: latest
 - name: jinja2
   version: latest

inbound_services:
 - channel_presence

builtins:
 - deferred: on